linkedin:
  keywords: "software engineer"
  location: "Bengaluru"
  distance: 40
  # 1 = Internship, 2 = Entry-level, 3 = Associate, 4 = Mid-Senior level, 5 = Director, 6 = Executive
  # Add multiple comma-separated values
  experience_levels: "2"

  # Optional: '1' is On-site, '2' is Remote, '3' is Hybrid. Leave blank for all.
  f_WT: "1,2,3"

  company_ids: []
  easy_apply: false # Set it to true, if ONLY easy apply jobs wanted
  results_wanted: 100
  filter_out_companies:
    - "Wipro"
    - "Infosys"
    - "Turing"
    - "Accenture services Pvt Ltd"

app:
  resume_file: Name_Resume.pdf
  min_ai_score: 6
  gemini_model: "gemini-3.1-flash-lite-preview"
  rate_limits:
    rpm: 15
    rpd: 500
