linkedin:
  keywords: "software engineer"
  location: "Bengaluru"
  distance: 40
  # Target 2-3 years of experience (LinkedIn code '2')
  experience_levels: "2"

  # Optional: '1' is On-site, '2' is Remote, '3' is Hybrid. Leave blank for all.
  f_WT: "1,2,3"

  company_ids: []
  easy_apply: false
  results_wanted: 100
  filter_out_companies:
    - "Wipro"
    - "Infosys"
    - "Turing"
    - "Accenture services Pvt Ltd"

app:
  min_ai_score: 6
  gemini_model: "gemini-3.1-flash-lite-preview"
  rate_limits:
    rpm: 15
    rpd: 500
